#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# 100M lines / 2Gb hopefully enough history xD
HISTSIZE=100000000
HISTFILESIZE=2000000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# get rid of the tty "pause" functionality, so we can forward i-search
stty start undef
stty stop undef

# source aliases from a separate file, we have many
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
# and centralize adding things to my PATH
if [ -f ~/.set_path ]; then
    . ~/.set_path
fi
if [ -f ~/.bash_completion ]; then
    . ~/.bash_completion
fi

# set a basic prompt
PS1='[\u@\h \W]\n\$ '

# and if we have liquidprompt, set and even better prompt
[[ $- = *i* ]] \
    && [[ -f "/home/bbeltr1/developer/liquidprompt/liquidprompt" ]] \
    && source /home/bbeltr1/developer/liquidprompt/liquidprompt

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/bbeltr1/.miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/bbeltr1/.miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/bbeltr1/.miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/bbeltr1/.miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

if [ -f "/home/bbeltr1/.passwords" ]; then
    . /home/bbeltr1/.passwords
fi

if [ -f "/usr/share/doc/fzf/examples/key-bindings.bash" ]; then
   source /usr/share/doc/fzf/examples/key-bindings.bash
   source /usr/share/doc/fzf/examples/completion.bash
fi
