#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# 100M lines / 2Gb hopefully enough history xD
HISTSIZE=100000000
HISTFILESIZE=2000000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# get rid of the tty "pause" functionality, so we can forward i-search
stty start undef
stty stop undef

# source aliases from a separate file, we have many
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
# and centralize adding things to my PATH
if [ -f ~/.set_path ]; then
    . ~/.set_path
fi

# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
# customize bash completion
if [ -f ~/.bash_completion ]; then
    . ~/.bash_completion
fi

# set a basic prompt
PS1='[\u@\h \W]\n\$ '

# and if we have liquidprompt, set an even better prompt
[[ $- = *i* ]] \
    && [[ -f "${HOME}/developer/liquidprompt/liquidprompt" ]] \
    && source "${HOME}/developer/liquidprompt/liquidprompt"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("${HOME}/.miniconda/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "${HOME}/.miniconda/etc/profile.d/conda.sh" ]; then
        . "${HOME}/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="${HOME}/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[ -f "${HOME}/.passwords" ] && . ${HOME}/.passwords
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
complete -C /opt/homebrew/bin/terraform terraform
