# Disable shellcheck's recursive sourcing and an error caused by the
# "conda-managed" section.
# shellcheck shell=bash disable=SC1091,SC2181

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# 100M lines / 2Gb hopefully enough history xD
HISTSIZE=100000000
HISTFILESIZE=2000000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# get rid of the tty "pause" functionality, so we can forward i-search
stty start undef
stty stop undef

# source aliases from a separate file, we have many
if [ -f "${HOME}/.bash_aliases" ]; then
    . "${HOME}/.bash_aliases"
fi
# and centralize adding things to my PATH
if [ -f "${HOME}/.set_path" ]; then
    . "${HOME}/.set_path"
fi

# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
elif command -v brew >/dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    . "$(brew --prefix)/etc/bash_completion"
fi

# customize bash completion
if [ -f "${HOME}/.bash_completion" ]; then
    . "${HOME}/.bash_completion"
fi

# set a basic prompt
PS1='[\u@\h \W]\n\$ '

# Use the "starship" prompt if we have it.
[[ -n $(which starship) ]] && eval "$(starship init bash)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("${HOME}/.miniconda/bin/conda" 'shell.bash' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "${HOME}/.miniconda/etc/profile.d/conda.sh" ]; then
        source "${HOME}/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="${HOME}/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[[ -f "${HOME}/.passwords" ]] && source "${HOME}/.passwords"
[[ -f "${HOME}/.fzf.bash" ]] && source "${HOME}/.fzf.bash"
[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
