# shellcheck shell=bash disable=SC2164

# for sanity
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Bazel should always secretly be Bazelisk if possible.
alias bazel=bazelisk

# for a beep
alias beep='play -qn synth 1 sine 800 vol 1 '

# Use the mac names for our copy buffer commands. wl-copy is a Wayland
# replacement for xclip (requires the wl-clipboard package).
if [[ -z "$(which pbcopy)" ]]; then
    alias pbcopy='wl-copy'
    alias pbpaste='wl-paste'
fi

# nvim does not provide a dedicated executable for diff'ing
if [[ -x "$(command -v nvim)" ]]; then
    alias vimdiff='nvim -d'
fi

# makes all aliases accessible via sudo
alias sudo='sudo '

# Always give me a python that makes sense.
_should_alias_python_to_python3=false
if [[ -z "$(which python)" && -n "$(which python3)" ]]; then
    _should_alias_python_to_python3=true
fi
if [[ -x "$(command -v lsb_release)" ]] && ! lsb_release -a | grep -q Debian; then
    _should_alias_python_to_python3=true
fi
if [[ "$_should_alias_python_to_python3" = true ]]; then
    if [[ -z "$(ls ~/.miniconda*)" ]]; then
        alias python='python3'
        if [[ -n "$(which pip3)" ]]; then
            alias pip='pip3'
        fi
    fi
fi
unset _should_alias_python_to_python3

WORKTREE_ROOT="${HOME}/developer/dbSDK"
# When we create a new worktree, we immediately kick off a minimal target that
# triggers the most expensive repository rules (python and ruff).
INITIAL_TARGET="//tools:workspace_test"
if [[ ! -d "${WORKTREE_ROOT}" ]]; then
    # Try one alternative directory just in case.
    WORKTREE_ROOT="${HOME}/dbSDK"
fi

# Convenience no-op function for when we want to print a message only in bash
# debug---i.e., `set -x`--- mode. Basically a more semantically-reasonable way
# to do something like `echo "Debug message" >/dev/null`.
_INFO() {
    # shellcheck disable=SC2317
    unused() {
        :
    }
}

# Instantiate Git worktree aliases for Digital Biology only if the WORKTREE_ROOT
# exists.
if [[ -d "${WORKTREE_ROOT}" ]]; then
    gtw() {
        cd "${WORKTREE_ROOT}"
        ls
    }
    # Implementation of `hgd`. Executes in a subshell in order to use `set`, and
    # prints *only* the final directory that should be `cd`'d to to stdout on
    # success---which means we must be careful to redirect the output of all
    # commands when updating this function!
    _hgd() { echo "$(
        worktree_path="${WORKTREE_ROOT}/$1"
        main_path="${WORKTREE_ROOT}/main"
        requested_ref="refs/heads/$1"
        main_ref="refs/heads/main"
        set -euox pipefail
        if [[ -d "${worktree_path}" ]]; then
            _INFO "Worktree exists, taking you there!" &&
                cd "${worktree_path}" &&
                pwd
            exit $?
        fi
        _INFO "Fetching 'origin' to ensure we know if the branch exists!"
        git fetch origin >/dev/null
        if git show-ref --verify --quiet "${requested_ref}"; then
            _INFO "Checking out existing branch...$1" &&
                git worktree add "${worktree_path}" "$1" >/dev/null
        else
            if ! git show-ref --verify --quiet "${main_ref}"; then
                _INFO "There does not seem to be a 'main' branch...please make one!"
                exit 1
            fi
            if [[ ! -d "${main_path}" ]]; then
                _INFO "There does not appear to be a worktree for the main branch...please make one!"
                exit 2
            fi
            _INFO "Pulling upstream changes to main before creating new branch!"
            if ! { cd "${main_path}" && git pull upstream main >/dev/null; }; then
                _INFO "Failed to pull upstream changes to main, please update 'main' then re-run 'hgd'!"
                exit 3
            fi
            _INFO "Creating new worktree on fresh branch based on 'main'!"
            if ! git worktree add "${worktree_path}" main -b "$1" >/dev/null; then
                _INFO "Failed to create worktree!"
                exit 4
            fi
        fi
        cd "${worktree_path}"

        _INFO "Pulling/updating all submodules..."
        git submodule update --init --recursive >/dev/null 2>&1

        _INFO "Kicking off some slow repository rules in the background..."
        _INFO "...it may take up to 5min for these to finish!"
        bazel build $INITIAL_TARGET >/dev/null 2>&1 &
        pwd
    )"; }
    hgd() {
        local worktree_path
        local subshell_exit_code
        worktree_path="$(_hgd "$1")"
        subshell_exit_code="$?"
        [[ -d "${worktree_path}" ]] &&
            echo "Taking you to ${worktree_path} in this shell..." &&
            cd "${worktree_path}"
        return "${subshell_exit_code}"
    }

    _exists_pr() {
        [[ "$#" -eq 2 ]] || return 255
        gh pr list --search "is:pr $2 head:$1" --json headRefName |
            python -c 'import sys, json; [print(o["headRefName"]) for o in json.load(sys.stdin)]' |
            grep -q "^$1$"
        return $?
    }
    hgdelete() {
        local worktree_path
        worktree_path="${WORKTREE_ROOT}/$1"
        if [[ "$2" != "-f" ]]; then
            local failed=false
            if _exists_pr "$1" "is:open"; then
                failed=true
                echo "ERROR: Found open PR with 'gh pr list --search \"is:pr is:open head:$1\"'"
            fi
            if ! _exists_pr "$1" "is:closed"; then
                failed=true
                echo "ERROR: Closed PR not found with 'gh pr list --search \"is:pr is:closed head:$1\"'"
            fi
            if [[ "$failed" = true ]]; then
                echo "Pass \"-f\" flag to ignore this and still attempt removal."
                echo "WARNING: \"-f\" flag FORCES worktree and local branch+remote deletion!"
                return 1
            fi
        fi
        if [[ -d "${worktree_path}" ]]; then
            echo -n "Attempting to remove git worktree at ${worktree_path}..."
            if ! git worktree remove "$2" "${worktree_path}"; then
                echo "FAILED. Pass '-f' to force."
                return 2
            else
                echo "Success!"
            fi
        fi
        [[ "$2" == "-f" ]] && d_flag="-D" || d_flag="-d"
        echo -n "Attempting to force-delete local branch with 'git branch $d_flag $1'..."
        if ! git branch "$d_flag" "$1"; then
            echo "FAILED. Pass '-f' to upgrade to use 'git branch -D'."
            return 3
        else
            echo "Success!"
        fi
        echo -n "Attempting to delete corresponding upstream branch: origin/$1..."
        if ! git push -d origin "$1"; then
            return 4
        fi
        echo "Successfully scrubbed all references to $1"
    }
fi
